/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:670057:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
    saveStrings(textfield1.getText(), lines);  //save the data to output file called spectrum.txt 
} //_CODE_:button1:670057:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:851379:
  //println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
  
} //_CODE_:textfield1:851379:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 1383, 22, 113, 59);
  button1.setText("save file");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
  textfield1 = new GTextField(this, 1336, 119, 160, 30, G4P.SCROLLBARS_NONE);
  textfield1.setText("spectrum1.txt");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 1334, 92, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("file name:");
  label1.setTextBold();
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField textfield1; 
GLabel label1; 
